# Generated by Django 5.2.4 on 2025-08-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_movie_release_date_movie_language_movie_rated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
