# Generated by Django 5.2.4 on 2025-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='imdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
